# Generated by Django 5.1.1 on 2025-07-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrousels',
            fields=[
                ('carrousel_id', models.AutoField(primary_key=True, serialize=False)),
                ('carrousel_title', models.CharField(blank=True, max_length=150, null=True)),
                ('carrousel_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'carrousels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrouselsitems',
            fields=[
                ('carrousel_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_item_name', models.CharField(blank=True, max_length=60, null=True)),
                ('car_item_description', models.CharField(blank=True, max_length=300, null=True)),
                ('car_item_image', models.ImageField(upload_to='carrousels_images/')),
                ('car_item_categorie', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'carrouselsitems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nom_categorie', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.PositiveIntegerField()),
                ('total', models.FloatField()),
                ('statut_commande', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'commandes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagesProduits',
            fields=[
                ('id_image_produit', models.AutoField(primary_key=True, serialize=False)),
                ('image_produit', models.ImageField(upload_to='produits_images/')),
            ],
            options={
                'db_table': 'images_produits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=80)),
                ('description_produit', models.CharField(blank=True, max_length=1000, null=True)),
                ('categorie', models.CharField(blank=True, max_length=50, null=True)),
                ('prix_produit', models.IntegerField()),
                ('texte_optionnel', models.CharField(blank=True, max_length=200, null=True)),
                ('quantite_produit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'produits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sectionitems',
            fields=[
                ('sections_items_id', models.AutoField(primary_key=True, serialize=False)),
                ('optional_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('item_position', models.IntegerField(blank=True, null=True)),
                ('item_image', models.ImageField(upload_to='sections_images/')),
                ('item_name', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'sectionitems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section_slogan', models.CharField(blank=True, max_length=1000, null=True)),
                ('section_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sections',
                'managed': False,
            },
        ),
    ]
